export type MakaveliPriceMode = "fixed" | "from" | "custom" | "referral" | "coming_soon";

export type MakaveliService = {
  slug: string;
  name: string;
  category: string;
  price?: number;
  priceLabel?: string;
  priceMode: MakaveliPriceMode;
  description: string;
  features: string[];
  suitableFor: string;
  duration?: number;
  booking: "pay" | "request";
  status: "available" | "request_only" | "coming_soon";
};

const fixed = (slug: string, name: string, category: string, price: number, description: string, features: string[], suitableFor: string, duration = 60): MakaveliService => ({ slug, name, category, price, priceMode: "fixed", description, features, suitableFor, duration, booking: "pay", status: "available" });

export const MAKAVELI_SERVICES: MakaveliService[] = [
  fixed("express-relaxation-massage","Express Relaxation Massage","Core Wellness & Recovery",5000,"A short, accessible relaxation experience for first-time and after-work guests.",["Relaxation-focused session","Guest preference check","Calm wellness environment","Post-session hydration guidance"],"First-time guests, professionals and people seeking a quick reset",45),
  fixed("back-shoulder-recovery","Back & Shoulder Recovery","Core Wellness & Recovery",6000,"Focused upper-body recovery experience for everyday muscular tension.",["Back-focused session","Shoulder and upper-back attention","Pressure preference","Recovery recommendations"],"Desk workers, drivers and professionals",60),
  fixed("neck-upper-body-relief","Neck & Upper-Body Relief","Core Wellness & Recovery",5000,"Targeted neck, shoulder and upper-back relaxation.",["Neck-area relaxation","Shoulder focus","Upper-back attention","Gentle techniques"],"Professionals and frequent phone/computer users",45),
  fixed("foot-leg-recovery","Foot & Leg Recovery","Core Wellness & Recovery",5000,"Lower-body reset for people who stand, walk or work on their feet.",["Foot relaxation","Lower-leg focus","Recovery-oriented massage","Pressure preference"],"People with demanding standing or walking routines",45),
  fixed("gentle-mobility-stretch","Gentle Mobility & Stretch","Core Wellness & Recovery",5000,"Guided gentle movement and stretching for general wellness.",["Basic mobility check","Guided gentle stretching","Comfort adjustments","Mobility recommendations"],"Guests seeking gentle movement support",45),
  fixed("muscle-recovery","Muscle Recovery","Core Wellness & Recovery",7000,"Recovery-focused session for active guests and post-activity relaxation.",["Targeted muscle recovery","Recovery techniques","Pressure preference","Post-activity guidance"],"Active individuals and training guests",60),
  fixed("private-relaxation","Private Relaxation Session","Core Wellness & Recovery",8000,"A more private, personalized relaxation experience.",["Private session environment","Personalized focus","Guest preference assessment","Extended wellness experience"],"Guests seeking privacy and personalization",60),
  fixed("aromatherapy-relaxation","Aromatherapy Relaxation","Core Wellness & Recovery",8000,"Sensory relaxation experience with guest-selected aromatherapy preference.",["Relaxation-focused session","Aromatherapy experience","Scent preference","Calm environment"],"Guests seeking a premium sensory experience",60),
  fixed("express-beauty-grooming","Express Beauty & Grooming","Beauty & Personal Care",5000,"A quick personal-care refresh in a hospitality wellness environment.",["Express grooming","Personal-care refresh","Guest preference check","Upgrade pathway"],"Guests preparing for work, travel or social occasions",45),
  fixed("basic-manicure","Basic Manicure","Beauty & Personal Care",4000,"Basic hand and nail-care experience.",["Nail cleaning","Nail shaping","Cuticle care","Hand-care finish"],"Guests seeking a simple hand-care refresh",45),
  fixed("basic-pedicure","Basic Pedicure","Beauty & Personal Care",5000,"Basic foot and nail-care experience.",["Foot soak","Nail cleaning","Nail shaping","Basic foot care"],"Guests seeking foot-care and relaxation",60),
  fixed("facial-skin-refresh","Facial & Skin Refresh","Beauty & Personal Care",7000,"A basic facial refresh with a relaxation component.",["Basic facial cleanse","Skin refresh","Gentle exfoliation where appropriate","Aftercare guidance"],"Guests seeking a simple skin refresh",60),
  fixed("scalp-head-relaxation","Scalp & Head Relaxation","Beauty & Personal Care",5000,"Head and scalp-focused relaxation with neck and shoulder attention.",["Scalp relaxation","Head massage","Neck/shoulder relaxation","Calm sensory experience"],"Guests seeking a short relaxation experience",45),
  fixed("couples-wellness-session","Couples Wellness Session","Couples & Private",15000,"A coordinated two-person wellness experience.",["Two-person experience","Coordinated relaxation","Guest preferences","Shared wellness environment"],"Couples and partners",60),
  fixed("private-couples-relaxation","Private Couples Relaxation","Couples & Private",18000,"Private couples relaxation with premium ambience.",["Private couples experience","Personalized relaxation","Premium ambience","Extended experience"],"Couples seeking privacy",75),
  fixed("romantic-wellness-experience","Romantic Wellness Experience","Couples & Private",20000,"A premium private wellness experience for special occasions.",["Private wellness setting","Couples relaxation","Romantic ambience","Hospitality add-ons"],"Anniversaries, dates and special occasions",90),
  fixed("private-wellness-package","Private Wellness Package","Couples & Private",15000,"A private combination of qualifying wellness services.",["Multiple wellness elements","Private experience","Personalized selection","Relaxation and recovery"],"Guests seeking a bundled private experience",90),
  fixed("hotel-guest-wellness","Hotel Guest Wellness Package","Hospitality",10000,"Convenient wellness designed around a hotel guest stay.",["Guest-focused session","Convenient scheduling","Relaxation/recovery service","Hospitality integration"],"Hotel and lodging guests",60),
  { slug:"in-room-wellness-service",name:"In-Room Wellness Service",category:"Hospitality",price:12000,priceLabel:"From ₦12,000",priceMode:"from",description:"Guest-room wellness service where operationally available.",features:["Guest-room service where available","Travel-friendly wellness","Personalized session","Hospitality convenience"],suitableFor:"Guests requesting in-room service",duration:60,booking:"request",status:"request_only" },
  fixed("weekend-wellness-package","Weekend Wellness Package","Hospitality",20000,"A weekend combination of relaxation and wellness experiences.",["Weekend relaxation","Service combination","Hospitality experience","Repeat-visit incentive"],"Weekend guests and local customers",120),
  fixed("business-traveller-recovery","Business Traveller Recovery Package","Hospitality",15000,"A compact recovery experience for business travellers.",["Targeted recovery","Back/shoulder focus","Foot/leg option","Short-stay friendly"],"Business travellers and short-stay guests",90),
  fixed("executive-guest-wellness","Executive Guest Wellness Package","Hospitality",20000,"Premium personalized wellness for executive guests.",["Premium private experience","Personalized service","Extended relaxation","Hospitality integration"],"Executive and premium hospitality guests",90),
  fixed("womens-relaxation","Women's Relaxation Package","Women's Wellness",10000,"Comfort-first relaxation experience with optional beauty add-ons.",["Relaxation-focused session","Personalized preferences","Comfort-first environment","Beauty add-on pathway"],"Women seeking a dedicated relaxation experience",60),
  fixed("market-woman-recovery","Market-Woman Recovery Session","Women's Wellness",5000,"Affordable recovery for women with physically demanding daily routines.",["Affordable entry","Foot/leg recovery","Back/shoulder option","Short recovery format"],"Traders and women with demanding routines",45),
  fixed("post-work-relaxation","Post-Work Relaxation","Women's Wellness",5000,"Convenient after-work relaxation experience.",["Quick relaxation","Neck/shoulder focus","Foot/leg option","Convenient scheduling"],"After-work guests",45),
  fixed("ladies-wellness-day","Ladies' Wellness Day","Women's Wellness",20000,"A multi-service wellness day with beauty and recovery options.",["Multiple wellness experiences","Beauty option","Relaxation","Hospitality experience"],"Friends, sisters and group wellness days",180),
  fixed("mother-daughter-wellness","Mother & Daughter Wellness Session","Women's Wellness",15000,"A shared two-person wellness experience.",["Two-person experience","Relaxation","Shared wellness activity","Beauty add-on"],"Mothers and daughters",60),
  fixed("mens-recovery","Men's Recovery Session","Men's Wellness",7000,"Targeted recovery experience for men.",["Back/shoulder recovery","Foot/leg option","Relaxation","Pressure preference"],"Men seeking recovery and relaxation",60),
  fixed("executive-mens-wellness","Executive Men's Wellness","Men's Wellness",12000,"Premium private wellness for executives.",["Private experience","Back/shoulder focus","Neck/upper-body relaxation","Extended experience"],"Executives and professionals",75),
  fixed("sports-muscle-recovery","Sports & Muscle Recovery","Men's Wellness",8000,"Post-activity recovery experience.",["Post-activity recovery","Targeted muscle focus","Mobility component","Recovery recommendations"],"Active and sports-oriented guests",60),
  fixed("after-work-recovery","After-Work Recovery","Men's Wellness",6000,"Quick recovery after a demanding workday.",["Express recovery","Back/shoulder focus","Neck relaxation","Foot/leg option"],"Professionals and workers",45),
  fixed("mens-grooming-relaxation","Men's Grooming & Relaxation","Men's Wellness",10000,"Grooming and relaxation combined in a premium hospitality setting.",["Grooming experience","Relaxation service","Personal-care refresh","Premium ambience"],"Men preparing for work, travel or events",75),
  fixed("mobility-assessment","Mobility Assessment","Mobility & Recovery",5000,"Basic movement screening and wellness recommendations.",["Basic movement screening","Mobility discussion","Movement observations","General wellness recommendations"],"Guests wanting a mobility starting point",45),
  fixed("gentle-stretch-mobility","Gentle Stretch & Mobility Session","Mobility & Recovery",5000,"Guided stretching and gentle mobility work.",["Guided stretching","Gentle mobility","Comfort-based progression","Take-home movement suggestions"],"Guests seeking gentle mobility support",45),
  fixed("back-care-wellness","Back-Care Wellness Session","Mobility & Recovery",7000,"Back-focused wellness with gentle mobility.",["Back-focused wellness","Gentle mobility","Relaxation","Lifestyle/recovery guidance"],"Guests seeking general back-care wellness",60),
  fixed("joint-mobility-support","Joint-Mobility Support","Mobility & Recovery",7000,"Gentle movement and mobility-focused wellness.",["Gentle movement","Mobility focus","Comfort adjustments","General wellness guidance"],"Guests seeking movement support",60),
  fixed("post-activity-recovery","Post-Activity Recovery","Mobility & Recovery",8000,"Recovery after exercise or demanding physical activity.",["Recovery session","Muscle relaxation","Gentle mobility","Post-activity recommendations"],"Active guests",60),
  {slug:"professional-physiotherapy-referral",name:"Professional Physiotherapy Referral",category:"Mobility & Recovery",priceMode:"referral",description:"Referral pathway to an appropriately qualified professional where available.",features:["Initial wellness concern identification","Referral pathway","Qualified professional connection where available"],suitableFor:"Guests whose needs may require professional physiotherapy",booking:"request",status:"request_only"},
  {slug:"corporate-wellness-session",name:"Corporate Wellness Session",category:"Corporate & Group",price:10000,priceLabel:"From ₦10,000/person",priceMode:"from",description:"Employee wellness experience with group scheduling.",features:["Employee wellness","Group scheduling","Recovery/relaxation options","Corporate reporting options"],suitableFor:"Companies and teams",booking:"request",status:"request_only"},
  {slug:"executive-wellness-package",name:"Executive Wellness Package",category:"Corporate & Group",price:15000,priceLabel:"From ₦15,000/person",priceMode:"from",description:"Premium private wellness for executive groups and guests.",features:["Premium private wellness","Personalized service","Executive scheduling","Recovery/relaxation options"],suitableFor:"Executives and corporate leadership",booking:"request",status:"request_only"},
  {slug:"workplace-recovery-sessions",name:"Workplace Recovery Sessions",category:"Corporate & Group",price:50000,priceLabel:"From ₦50,000/group",priceMode:"from",description:"Short-format workplace recovery sessions for teams.",features:["On-site or designated-location format","Multiple participants","Short-format recovery","Corporate wellness activation"],suitableFor:"Workplaces and staff teams",booking:"request",status:"request_only"},
  {slug:"corporate-wellness-day",name:"Corporate Massage / Wellness Day",category:"Corporate & Group",price:100000,priceLabel:"From ₦100,000",priceMode:"from",description:"Group wellness activation with flexible service stations where available.",features:["Group wellness activation","Multiple service stations where available","Staff engagement","Flexible scheduling"],suitableFor:"Corporate events and staff wellness days",booking:"request",status:"request_only"},
  {slug:"team-wellness-experience",name:"Team Wellness Experience",category:"Corporate & Group",price:75000,priceLabel:"From ₦75,000",priceMode:"from",description:"Team-based relaxation, mobility and recovery experience.",features:["Team wellness","Relaxation","Mobility/recovery","Group experience"],suitableFor:"Teams and organizations",booking:"request",status:"request_only"},
  {slug:"event-wellness-activation",name:"Event Wellness Activation",category:"Corporate & Group",priceMode:"custom",priceLabel:"Custom quote",description:"Wellness station and guest engagement for events.",features:["Event wellness station","Guest engagement","Short wellness experiences","Custom event integration"],suitableFor:"Events, launches and activations",booking:"request",status:"request_only"},
  fixed("quick-reset","Quick Reset","Packages & Membership",5000,"Express wellness experience for repeatable everyday resets.",["Express wellness","Short-format experience","Repeat-visit pathway"],"Guests wanting a quick wellness reset",45),
  fixed("weekly-recovery-package","Weekly Recovery Package","Packages & Membership",18000,"Bundled weekly recovery pathway.",["Up to 3 qualifying sessions","Priority booking request","Personalized recommendations"],"Guests building a weekly routine"),
  fixed("monthly-wellness-package","Monthly Wellness Package","Packages & Membership",30000,"Monthly wellness allocation with service flexibility.",["Up to 5 qualifying sessions","Service-selection flexibility","Member experience benefits"],"Repeat wellness customers"),
  fixed("couples-wellness-package","Couples Wellness Package","Packages & Membership",25000,"Repeat couples wellness pathway.",["Two-person wellness","Repeat-visit structure","Couples-focused benefits"],"Couples and partners"),
  fixed("executive-package","Executive Wellness Package — Membership","Packages & Membership",40000,"Premium wellness membership pathway.",["Premium wellness sessions","Private experience options","Priority booking request","Personalized pathway"],"Executives and premium customers"),
  fixed("wellness-day-pass","Wellness Day Pass","Packages & Membership",20000,"Multi-service wellness-day experience.",["Multiple qualifying services","Full wellness-day experience","Beauty/recovery options","Hospitality integration"],"Guests seeking a fuller wellness day"),
  fixed("wellness-membership","Wellness Membership","Packages & Membership",50000,"Monthly wellness membership with member benefits.",["Monthly wellness allocation","Member benefits","Priority booking request","Personalized recommendations"],"Regular wellness customers"),
  fixed("vip-private-wellness-membership","VIP Private Wellness Membership","Packages & Membership",100000,"Premium private wellness membership.",["Premium private access","Personalized pathway","Priority scheduling request","VIP hospitality experience"],"VIP and high-frequency customers"),
  {slug:"nutrition-wellness-consultation",name:"Nutrition & Wellness Consultation",category:"Future Services",priceMode:"coming_soon",description:"Future qualified-practitioner wellness consultation.",features:["Qualified-practitioner pathway","Personalized consultation","Coming-soon service state"],suitableFor:"Customers seeking nutrition and wellness guidance",booking:"request",status:"coming_soon"},
  {slug:"healthy-refreshments-wellness-bar",name:"Healthy Refreshments / Wellness Bar",category:"Future Services",priceMode:"coming_soon",description:"Future wellness refreshment offering.",features:["Wellness refreshments","Menu-based pricing","Hospitality integration"],suitableFor:"Wellness and hospitality guests",booking:"request",status:"coming_soon"},
  {slug:"fitness-functional-training",name:"Fitness & Functional Training",category:"Future Services",price:5000,priceLabel:"From ₦5,000/session",priceMode:"from",description:"Future fitness and functional training pathway.",features:["Functional training","Movement coaching","Progressive pathway"],suitableFor:"Customers seeking fitness support",booking:"request",status:"coming_soon"},
  {slug:"personal-training",name:"Personal Training",category:"Future Services",price:8000,priceLabel:"From ₦8,000/session",priceMode:"from",description:"Future one-to-one training pathway.",features:["One-to-one coaching","Goal-based training","Progress tracking"],suitableFor:"Customers seeking personalized fitness coaching",booking:"request",status:"coming_soon"},
  {slug:"yoga-mobility-classes",name:"Yoga & Mobility Classes",category:"Future Services",price:5000,priceLabel:"From ₦5,000/session",priceMode:"from",description:"Future group movement and mobility classes.",features:["Guided movement","Mobility work","Group class format"],suitableFor:"Guests seeking guided movement",booking:"request",status:"coming_soon"},
  {slug:"recovery-performance-programs",name:"Recovery & Performance Programs",category:"Future Services",priceMode:"custom",priceLabel:"Custom programme pricing",description:"Future structured recovery and performance programs.",features:["Structured program","Progress tracking","Personalized pathway"],suitableFor:"Active customers and performance-focused guests",booking:"request",status:"coming_soon"},
  {slug:"wellness-retail-products",name:"Wellness Retail Products",category:"Future Services",priceMode:"coming_soon",description:"Future wellness retail collection.",features:["Curated products","Product-specific pricing","Hospitality retail integration"],suitableFor:"Wellness customers and guests",booking:"request",status:"coming_soon"},
  {slug:"integrated-wellness-fitness-membership",name:"Integrated Wellness + Fitness Membership",category:"Future Services",priceMode:"custom",priceLabel:"Custom membership tiers",description:"Future integrated wellness and fitness membership.",features:["Wellness services","Fitness pathway","Membership benefits"],suitableFor:"Customers seeking an integrated routine",booking:"request",status:"coming_soon"},
  fixed("wellness-reset","₦1,000 Wellness Reset","Campaign Offer",1000,"Introductory campaign experience designed to make Makaveli easy to try.",["Short introductory experience","Guest welcome","Basic preference check","Clear next-step recommendation"],"New customers and campaign traffic",20),
];

export const MAKAVELI_CATEGORIES = [...new Set(MAKAVELI_SERVICES.map((service) => service.category))];
export const getMakaveliService = (slug: string) => MAKAVELI_SERVICES.find((service) => service.slug === slug);
export const formatNGN = (value: number) => `₦${value.toLocaleString("en-NG")}`;
