import { createFileRoute } from "@tanstack/react-router";
import { createClient } from "@supabase/supabase-js";
import { createHmac, timingSafeEqual } from "node:crypto";

const SUPABASE_URL = process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? "https://vbqjvmnhdtdhmeeudqnn.supabase.co";
const SERVICE_ROLE = process.env.SUPABASE_SERVICE_ROLE_KEY;
const PAYSTACK_SECRET = process.env.PAYSTACK_SECRET_KEY ?? process.env.PAYSTACK_SECRET;
function validSignature(raw:string, signature:string){if(!PAYSTACK_SECRET||!signature)return false;const expected=createHmac("sha512",PAYSTACK_SECRET).update(raw).digest("hex");const a=Buffer.from(expected),b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b);}
export const Route=createFileRoute("/api/makaveli/paystack-webhook")({server:{handlers:{POST:async({request})=>{try{const raw=await request.text();if(!validSignature(raw,request.headers.get("x-paystack-signature")??""))return new Response("Unauthorized",{status:401});if(!SERVICE_ROLE)return new Response("Server not configured",{status:503});const event=JSON.parse(raw);if(event.event!=="charge.success")return Response.json({ok:true,ignored:true});const reference=String(event.data?.reference??"");if(!reference)return Response.json({ok:true,ignored:true});const client=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});const {data:booking}=await client.from("makaveli_bookings").select("*").eq("payment_reference",reference).maybeSingle();if(!booking)return Response.json({ok:true,ignored:true});const expected=Math.round(Number(booking.amount_ngn)*100);const paid=event.data?.status==="success"&&event.data?.currency==="NGN"&&Number(event.data?.amount)===expected&&String(event.data?.customer?.email??"").toLowerCase()===String(booking.customer_email).toLowerCase();if(paid)await client.from("makaveli_bookings").update({status:"paid",payment_status:"success",updated_at:new Date().toISOString()}).eq("id",booking.id);return Response.json({ok:true,paid});}catch(error){console.error("Makaveli Paystack webhook",error);return new Response("Bad request",{status:400});}}}}});
