import { createFileRoute } from "@tanstack/react-router";
import { createClient } from "@supabase/supabase-js";
import { getMakaveliService } from "@/lib/makaveliCatalog";

const SUPABASE_URL = process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? "https://vbqjvmnhdtdhmeeudqnn.supabase.co";
const SERVICE_ROLE = process.env.SUPABASE_SERVICE_ROLE_KEY;
function clean(value: unknown,max=1000){return typeof value === "string" ? value.trim().slice(0,max) : "";}
function reference(){return `MKV-R-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;}
export const Route = createFileRoute("/api/makaveli/booking")({server:{handlers:{POST:async({request})=>{try{if(!SERVICE_ROLE)return Response.json({ok:false,error:"Booking service is not configured server-side."},{status:503});const body=await request.json().catch(()=>({}));const service=getMakaveliService(clean(body.serviceSlug,120));const name=clean(body.name,120),email=clean(body.email,180).toLowerCase(),phone=clean(body.phone,40);if(!service)return Response.json({ok:false,error:"Service not found"},{status:404});if(!name||!email||!phone)return Response.json({ok:false,error:"Name, email and phone are required."},{status:400});const client=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});const bookingReference=reference();const {error}=await client.from("makaveli_bookings").insert({booking_reference:bookingReference,service_slug:service.slug,service_name:service.name,amount_ngn:service.price??0,customer_name:name,customer_email:email,customer_phone:phone,preferred_date:clean(body.preferredDate,20)||null,preferred_time:clean(body.preferredTime,40)||null,notes:clean(body.notes,1000)||null,status:"request_only"});if(error)throw error;return Response.json({ok:true,bookingReference,serviceName:service.name});}catch(error){console.error("Makaveli booking",error);return Response.json({ok:false,error:error instanceof Error?error.message:"Unable to submit booking"},{status:500});}}}}});
