import { createFileRoute } from "@tanstack/react-router";
import { createClient } from "@supabase/supabase-js";
import { createHmac, timingSafeEqual } from "node:crypto";

const SUPABASE_URL = process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? "https://vbqjvmnhdtdhmeeudqnn.supabase.co";
const SERVICE_ROLE = process.env.SUPABASE_SERVICE_ROLE_KEY;
const PAYSTACK_SECRET = process.env.PAYSTACK_SECRET_KEY ?? process.env.PAYSTACK_SECRET;
function validSignature(raw:string, signature:string){if(!PAYSTACK_SECRET||!signature)return false;const expected=createHmac("sha512",PAYSTACK_SECRET).update(raw).digest("hex");const a=Buffer.from(expected),b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b);}

export const Route=createFileRoute("/api/makaveli/paystack-webhook")({server:{handlers:{POST:async({request})=>{try{const raw=await request.text();if(!validSignature(raw,request.headers.get("x-paystack-signature")??""))return new Response("Unauthorized",{status:401});if(!SERVICE_ROLE)return new Response("Server not configured",{status:503});const event=JSON.parse(raw);if(event.event!=="charge.success")return Response.json({ok:true,ignored:true});const reference=String(event.data?.reference??"");if(!reference)return Response.json({ok:true,ignored:true});const client=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});const {data:bookingByReference,error:bookingReferenceError}=await client.from("makaveli_bookings").select("*").eq("booking_reference",reference).maybeSingle();if(bookingReferenceError)throw bookingReferenceError;let booking=bookingByReference;if(!booking){const {data:legacyBooking,error:legacyLookupError}=await client.from("makaveli_bookings").select("*").eq("payment_reference",reference).maybeSingle();if(legacyLookupError)throw legacyLookupError;booking=legacyBooking;}if(!booking)return Response.json({ok:true,ignored:true});const expected=Math.round(Number(booking.amount_ngn)*100);const paid=event.data?.status==="success"&&event.data?.currency==="NGN"&&Number(event.data?.amount)===expected&&String(event.data?.customer?.email??"").toLowerCase()===String(booking.customer_email).toLowerCase();if(!paid)return Response.json({ok:true,paid:false});const now=new Date().toISOString();const {error:bookingUpdateError}=await client.from("makaveli_bookings").update({status:"confirmed",payment_status:"success",payment_reference:reference,updated_at:now}).eq("id",booking.id);if(bookingUpdateError)throw bookingUpdateError;

const serviceSku=`MAKAVELI:${booking.service_slug}`;
const {data:payment,error:paymentError}=await client.from("payments").upsert({user_id:null,amount:Number(booking.amount_ngn),currency:"NGN",status:"success",plan_type:booking.service_name,paystack_ref:reference,customer_email:booking.customer_email,product_sku:serviceSku,funnel_origin:"makaveli_wellness",gross_amount:Math.round(Number(booking.amount_ngn)*100),paid_at:event.data?.paid_at??now,gateway_response:event.data?.gateway_response??"Approved",reconciled:true,reconciled_at:now,settlement_status:"pending",metadata:{booking_reference:booking.booking_reference,service_slug:booking.service_slug,service_name:booking.service_name,preferred_date:booking.preferred_date,preferred_time:booking.preferred_time,practitioner_preference:booking.practitioner_preference}},{onConflict:"paystack_ref"}).select("id").maybeSingle();
if(paymentError)throw paymentError;if(!payment)throw new Error("Canonical payment record could not be persisted");
const {error:revenueError}=await client.from("revenue_events").upsert({payment_reference:reference,payment_id:payment.id,amount:Number(booking.amount_ngn),currency:"NGN",email:booking.customer_email,product_slug:serviceSku,status:"success"},{onConflict:"payment_reference"});if(revenueError)throw revenueError;
let {data:fulfillment,error:fulfillmentLookupError}=await client.from("resofit_fulfillment_orders").select("id,status").eq("payment_reference",reference).maybeSingle();if(fulfillmentLookupError)throw fulfillmentLookupError;
if(!fulfillment){const created=await client.from("resofit_fulfillment_orders").insert({payment_id:payment.id,payment_reference:reference,customer_id:null,customer_email:booking.customer_email,status:"confirmed",hub_code:"SERVICE",currency:"NGN",total_amount:Number(booking.amount_ngn),metadata:{mode:"service",source:"makaveli",booking_reference:booking.booking_reference,service_slug:booking.service_slug,service_name:booking.service_name}}).select("id,status").single();if(created.error)throw created.error;fulfillment=created.data;}else if(fulfillment.status!=="confirmed"){const {error:fulfillmentUpdateError}=await client.from("resofit_fulfillment_orders").update({status:"confirmed",updated_at:now}).eq("id",fulfillment.id);if(fulfillmentUpdateError)throw fulfillmentUpdateError;}
const {data:existingItem,error:itemLookupError}=await client.from("resofit_fulfillment_items").select("id").eq("fulfillment_order_id",fulfillment.id).eq("sku",serviceSku).limit(1);if(itemLookupError)throw itemLookupError;if(!existingItem?.length){const {error:itemInsertError}=await client.from("resofit_fulfillment_items").insert({fulfillment_order_id:fulfillment.id,product_id:null,sku:serviceSku,quantity:1,metadata:{mode:"service",booking_reference:booking.booking_reference,service_name:booking.service_name}});if(itemInsertError)throw itemInsertError;}
const {data:existingEvent,error:eventLookupError}=await client.from("resofit_fulfillment_events").select("id").eq("fulfillment_order_id",fulfillment.id).eq("to_status","confirmed").contains("detail",{booking_reference:booking.booking_reference}).limit(1);if(eventLookupError)throw eventLookupError;if(!existingEvent?.length){const {error:eventInsertError}=await client.from("resofit_fulfillment_events").insert({fulfillment_order_id:fulfillment.id,from_status:"payment_pending",to_status:"confirmed",detail:{payment_reference:reference,booking_reference:booking.booking_reference,service_slug:booking.service_slug}});if(eventInsertError)throw eventInsertError;}
return Response.json({ok:true,paid:true,bookingReference:booking.booking_reference,reference,fulfillmentStatus:"confirmed"});}catch(error){console.error("Makaveli Paystack webhook",error);return new Response("Bad request",{status:400});}}}}});
