import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, BookOpen, Scale, ShieldCheck, Sparkles } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";

const DATA: Record<string,{title:string;intro:string;items:string[]}> = {
 casebook:{title:"Casebook",intro:"Structured case intelligence with status, evidence, chronology and legal analysis.",items:["featured","latest","resolved","ongoing","disputed","business","family","property","commercial","employment","technology","digital-commerce"]},
 "coach-buchi":{title:"Coach Buchi",intro:"Founder chronology and case studies, with private matters protected and public claims carefully classified.",items:["chronology","origins","education","entrepreneurship","resonance-fitness","business-challenges","hotel-years","family-disputes","legal-battles","rebuilding"]},
 seasons:{title:"Seasons",intro:"The evolving founder narrative from The Last Man Standing through Legacy.",items:["the-last-man-standing","the-builder","the-entrepreneur","the-wars","candy","the-iphone","resofit","resoflex","chatb2k","lord-b2k","the-ecosystem","the-rebuild","the-revenue-machine","the-legacy"]},
 legal:{title:"Legal Research",intro:"Legal issue areas for research and educational analysis. Current law must be verified against authoritative sources.",items:["contract","company","commercial","employment","property","debt","intellectual-property","privacy","data-protection","consumer","digital-commerce","technology","ai","defamation","family","dispute-resolution"]},
 research:{title:"Research",intro:"Primary and secondary research organized for evidence-first analysis.",items:["legislation","regulations","cases","judgments","regulatory-guidance","legal-updates"]},
 evidence:{title:"Evidence",intro:"Evidence indexing, chronology, source registers and provenance. Sensitive material remains access-controlled.",items:["index","chronology","documents","communications","transactions","system-records","source-register","provenance"]},
 governance:{title:"Governance",intro:"Authorities, permissions, controls, audits, risk and decisions.",items:["principles","policies","controls","authorities","permissions","audit","risk-register","incident-register","decision-register"]},
 ecosystem:{title:"Ecosystem",intro:"Legal and governance relationships across the ResoFit technology and commerce architecture.",items:["resofit","resoflex","resonance-fitness","chatb2k","lord-b2k","commerce","payments","attribution","automation","content","customer-data","architecture"]},
 "case-studies":{title:"Case Studies",intro:"Evidence-backed lessons from business, technology, automation, commerce, revenue and production.",items:["business","technology","automation","commerce","revenue","attribution","ai","production","recovery"]},
 risk:{title:"Risk",intro:"Risk states and mitigation controls across legal, commercial, technical, operational and privacy domains.",items:["active","controlled","accepted","resolved","legal","commercial","technical","operational","privacy"]},
 principles:{title:"Principles",intro:"The operating philosophy behind evidence-first governance and resilient systems.",items:["lord-b2k","resilience","evidence-first","zero-assumption","separation-of-authority","auditability","recovery"]},
 tools:{title:"Tools",intro:"Governance tools for timelines, case mapping, risk, evidence and decisions.",items:["timeline","case-map","risk-matrix","evidence-map","decision-log","governance-checklist"]},
 admin:{title:"Admin",intro:"Restricted governance workspace. Access controls apply; this public shell does not expose private evidence.",items:["cases","evidence","research","reviews","redactions","risk","governance","publishing","audit-log","access"]}
};

export const Route = createFileRoute("/legal/$section")({beforeLoad:({params})=>{if(!DATA[params.section])throw notFound()},component:LegalSection});

function LegalSection(){const{section}=Route.useParams();const d=DATA[section];return <div className="min-h-screen bg-background text-foreground"><SiteHeader/><main><section className="border-b border-border/60 bg-black"><div className="mx-auto max-w-6xl px-6 py-24"><Link to="/legal" className="inline-flex items-center gap-2 text-xs uppercase tracking-widest text-muted-foreground hover:text-gold"><ArrowLeft className="h-4 w-4"/> Legal</Link><p className="mt-12 text-xs uppercase tracking-[.3em] text-gold">Legal · Governance · Case Intelligence</p><h1 className="mt-4 font-display text-6xl sm:text-8xl">{d.title}</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-muted-foreground">{d.intro}</p></div></section><section className="py-16 sm:py-24"><div className="mx-auto max-w-6xl px-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{d.items.map(item=><Link key={item} to="/legal/$section/$subsection" params={{section,subsection:item}} className="group rounded-3xl border border-border/60 bg-card/20 p-6 transition-all hover:-translate-y-1 hover:border-gold/40"><div className="flex justify-between"><BookOpen className="h-5 w-5 text-gold"/><ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1"/></div><h2 className="mt-10 text-lg font-semibold capitalize">{item.replaceAll("-"," ")}</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Open section → evidence, analysis, governance and learning.</p></Link>)}</div></section></main><SiteFooter/></div>}