import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowRight, MapPin } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL as string|undefined;const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string|undefined;
const AREAS=["new-town","world-bank","ehimiri","bca-road","club-road","aba-township","ariaria","osisioma","umungasi","abayi","ogbor-hill","eziukwu-road","okigwe-road","faulks-road","aba-owerri-road","st-michaels-road"];
type Hub={id:string;slug:string;name:string;description:string|null;address:string|null;lga:string|null;rating:number|null;review_count:number;services:Array<{id:string;service_name:string}>};
async function locator<T>(params:Record<string,string|number|undefined>){if(!SUPABASE_URL)throw new Error("Wellness locator is not configured");const q=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!=="")q.set(k,String(v));});const r=await fetch(`${SUPABASE_URL}/functions/v1/wellness-locator?${q}`,{headers:SUPABASE_KEY?{apikey:SUPABASE_KEY}:undefined});if(!r.ok)throw new Error("Wellness locator failed");return r.json() as Promise<T>}
export const Route=createFileRoute("/wellness/$state/areas/$area")({loader:({params})=>{if(params.state!=="abia"||!AREAS.includes(params.area))throw notFound();return {area:params.area}},head:({params})=>({meta:[{title:`${params.area.replaceAll("-"," ")} Wellness — ResoFit`},{name:"description",content:`Discover wellness providers around ${params.area.replaceAll("-"," ")} in Abia State.`}],links:[{rel:"canonical",href:`https://resofit.fit/wellness/${params.state}/areas/${params.area}`}]}),component:AreaPage});
function AreaPage(){const {area}=Route.useLoaderData();const [results,setResults]=useState<Hub[]>([]);const [message,setMessage]=useState("Searching the live directory…");useEffect(()=>{void locator<{results:Hub[];count:number}>({action:"nearby",state:"abia",q:area.replaceAll("-"," "),radius_km:25}).then(d=>{setResults(d.results);setMessage(d.count?`${d.count} provider${d.count===1?"":"s"} found.`:"No indexed provider currently matches this area.")}).catch(()=>setMessage("Unable to search this area right now."))},[area]);const label=area.replaceAll("-"," ").replace(/\b\w/g,x=>x.toUpperCase());return <div className="min-h-screen bg-background"><SiteHeader/><main><section className="border-b border-border/60"><div className="mx-auto max-w-7xl px-6 py-20 md:py-28"><Link to="/wellness/$state" params={{state:"abia"}} className="text-xs uppercase tracking-widest text-muted-foreground hover:text-gold">← Abia Wellness</Link><p className="mt-8 text-xs uppercase tracking-[0.35em] text-gold">Abia · Area discovery</p><h1 className="mt-3 font-display text-6xl md:text-8xl">Wellness around {label}.</h1><p className="mt-6 max-w-2xl text-lg text-muted-foreground">{message} This area page is a discovery route, not a partnership or supplier gate.</p></div></section><section className="py-16"><div className="mx-auto max-w-7xl px-6"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{results.map(h=><article key={h.id} className="border border-border/60 p-6"><p className="text-xs uppercase tracking-[0.2em] text-gold">{h.lga??"Abia"}</p><h2 className="mt-2 font-display text-2xl">{h.name}</h2>{h.address&&<p className="mt-3 text-sm text-muted-foreground">{h.address}</p>}<div className="mt-4 flex flex-wrap gap-2">{h.services.map(s=><span key={s.id} className="border border-border px-2 py-1 text-xs">{s.service_name}</span>)}</div><Link to="/wellness/hubs/$slug" params={{slug:h.slug}} className="mt-6 inline-flex items-center gap-2 text-xs uppercase tracking-widest text-gold">View profile <ArrowRight className="h-4 w-4"/></Link></article>)}</div>{!results.length&&<div className="border border-border/60 p-10 text-center"><MapPin className="mx-auto h-6 w-6 text-gold"/><h2 className="mt-4 font-display text-3xl">Discovery gap — not a gate.</h2><p className="mt-3 text-sm text-muted-foreground">No provider is currently indexed against this area. The directory remains open to physical and online listings.</p></div>}</div></section></main><SiteFooter/></div>}
