import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check, MessageCircle } from "lucide-react";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { getMakaveliService, formatNGN } from "@/lib/makaveliCatalog";

export const Route = createFileRoute("/wellness/makaveli/services/$slug")({
  head: ({ params }) => { const service=getMakaveliService(params.slug); return { meta:[{title:`${service?.name ?? "Makaveli Wellness Service"} — Makaveli Wellness Services`},{name:"description",content:service?.description ?? "Makaveli Wellness Service"}],links:[{rel:"canonical",href:`https://resofit.fit/wellness/makaveli/services/${params.slug}`}]}; },
  component: ServiceDetail,
});

function ServiceDetail(){
 const {slug}=Route.useParams(); const service=getMakaveliService(slug);
 if(!service) return <div className="min-h-screen bg-background"><SiteHeader/><main className="mx-auto max-w-4xl px-6 py-32"><h1 className="font-display text-5xl">Service not found</h1><Link to="/wellness/makaveli/services" className="mt-8 inline-flex text-gold">Back to services</Link></main><SiteFooter/></div>;
 const price=service.priceMode === "fixed" && service.price ? formatNGN(service.price) : service.priceLabel ?? (service.priceMode === "referral" ? "Referral" : "Custom quote");
 const canPay=service.booking === "pay" && service.status === "available";
 return <div className="min-h-screen bg-background"><SiteHeader/><main>
  <section className="border-b border-border/60"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><Link to="/wellness/makaveli/services" className="inline-flex items-center gap-2 text-xs uppercase tracking-widest text-muted-foreground hover:text-gold"><ArrowLeft className="h-4 w-4"/>All services</Link><p className="mt-10 text-xs uppercase tracking-[.35em] text-gold">{service.category}</p><h1 className="mt-4 max-w-4xl font-display text-5xl leading-none md:text-8xl">{service.name}</h1><div className="mt-8 flex flex-wrap items-center gap-5"><span className="font-display text-3xl text-gold">{price}</span>{service.duration&&<span className="text-sm text-muted-foreground">{service.duration} minutes</span>}<span className="text-xs uppercase tracking-widest text-muted-foreground">{service.status === "coming_soon" ? "Coming soon" : service.booking === "pay" ? "Book & pay online" : "Booking request"}</span></div><p className="mt-8 max-w-2xl text-lg leading-relaxed text-muted-foreground">{service.description}</p><div className="mt-10 flex flex-wrap gap-3">{canPay ? <Link to="/wellness/makaveli/book" search={{service:service.slug}} className="inline-flex items-center gap-2 bg-gold px-7 py-4 text-xs font-semibold uppercase tracking-widest text-gold-foreground">Book & pay <ArrowRight className="h-4 w-4"/></Link> : <Link to="/wellness/makaveli/book" search={{service:service.slug}} className="inline-flex items-center gap-2 bg-gold px-7 py-4 text-xs font-semibold uppercase tracking-widest text-gold-foreground">Request booking <ArrowRight className="h-4 w-4"/></Link>}<a href="https://wa.me/2349032712393" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-border px-7 py-4 text-xs font-semibold uppercase tracking-widest"><MessageCircle className="h-4 w-4"/>WhatsApp</a></div></div></section>
  <section className="py-20"><div className="mx-auto grid max-w-6xl gap-14 px-6 md:grid-cols-[1fr_.7fr]"><div><p className="text-xs uppercase tracking-[.3em] text-gold">What the experience includes</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{service.features.map(f=><div key={f} className="border border-border/60 p-5"><Check className="h-4 w-4 text-gold"/><p className="mt-3 text-sm">{f}</p></div>)}</div></div><aside className="border border-border/60 bg-card/30 p-7"><p className="text-xs uppercase tracking-widest text-gold">Who it may suit</p><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{service.suitableFor}</p>{service.category === "Mobility & Recovery" && <p className="mt-6 border-t border-border/60 pt-5 text-xs leading-relaxed text-muted-foreground">Wellness service only. This page does not provide medical diagnosis or treatment.</p>}<Link to="/wellness/makaveli/services" className="mt-8 inline-flex items-center gap-2 text-xs uppercase tracking-widest text-gold">Explore more services <ArrowRight className="h-4 w-4"/></Link></aside></div></section>
 </main><SiteFooter/></div>;
}
