import type { WellnessPartnerLead } from "./partnerDiscovery";

/** Initial public-discovery seed. These records are prospects, not ResoFit-verified hubs. */
export const WELLNESS_DISCOVERY_SEED: WellnessPartnerLead[] = [
  { name: "DreamDaySpa", country: "Nigeria", state: "Rivers", city: "Port Harcourt", category: "spa", services: ["massage", "spa"], website: null, email: null, phone: "+2349131707258", source: "Go Africa Online", sourceUrl: "https://www.goafricaonline.com/ng/directory/spas-saunas", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.82 },
  { name: "Enoralifestyle Spa and Wellness Centre", country: "Nigeria", state: "Oyo", city: "Ibadan", category: "spa", services: ["spa", "wellness"], website: null, email: null, phone: "+2347035544194", source: "Go Africa Online", sourceUrl: "https://www.goafricaonline.com/ng/directory/spas-saunas", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.75 },
  { name: "Elixir Spa & Wellness Centre", country: "Nigeria", state: "Anambra", city: "Awka", category: "spa", services: ["spa", "wellness"], website: null, email: null, phone: "+2348087776338", source: "Go Africa Online", sourceUrl: "https://www.goafricaonline.com/ng/directory/spas-saunas", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.74 },
  { name: "EnVisage Spa and Salon", country: "Nigeria", state: "Lagos", city: "Victoria Island", category: "spa", services: ["spa", "beauty"], website: null, email: null, phone: "+2347068388822", source: "Go Africa Online", sourceUrl: "https://www.goafricaonline.com/ng/directory/spas-saunas", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.78 },
  { name: "Dr Spa Beauty and Wellness", country: "Nigeria", state: "Ogun", city: "Abeokuta", category: "spa", services: ["spa", "wellness"], website: null, email: null, phone: "+2348117700877", source: "Go Africa Online", sourceUrl: "https://www.goafricaonline.com/ng/directory/spas-saunas", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.70 },
  { name: "Citi Spa & Sauna", country: "Nigeria", state: "Lagos", city: "Ipaja", category: "spa", services: ["spa", "sauna"], website: null, email: null, phone: "+2347030572324", source: "Go Africa Online", sourceUrl: "https://www.goafricaonline.com/ng/directory/spas-saunas", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.70 },
  { name: "Royal Xtasy Spa", country: "Nigeria", state: "Lagos", city: "Victoria Island", category: "spa", services: ["spa", "massage"], website: null, email: null, phone: "+2349043094708", source: "BusinessList Nigeria", sourceUrl: "https://www.businesslist.com.ng/companies/spa", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.80 },
  { name: "Goldiva Aesthetic SPA", country: "Nigeria", state: "Edo", city: "Benin City", category: "spa", services: ["spa", "aesthetics"], website: null, email: null, phone: "+2348099169332", source: "BusinessList Nigeria", sourceUrl: "https://www.businesslist.com.ng/companies/spa", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.77 },
  { name: "Topaz House of Beauty Spa and Salon", country: "Nigeria", state: "FCT", city: "Abuja", category: "spa", services: ["spa", "beauty"], website: null, email: null, phone: null, source: "Fresha", sourceUrl: "https://www.fresha.com/lp/en/bt/spas-and-saunas/in/nigeria", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.84 },
  { name: "AJ's Beauty Lounge & Spa", country: "Ghana", state: "Greater Accra", city: "Accra", category: "spa", services: ["spa", "beauty"], website: null, email: null, phone: null, source: "Go Africa Online", sourceUrl: "https://www.goafricaonline.com/gh/directory/spas-saunas", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.72 },
  { name: "Ador Beauty Spa", country: "Ghana", state: "Greater Accra", city: "Accra", category: "spa", services: ["spa", "beauty"], website: null, email: null, phone: null, source: "Go Africa Online", sourceUrl: "https://www.goafricaonline.com/gh/directory/spas-saunas", verificationStatus: "discovered", partnershipStatus: "not_contacted", discoveryScore: 0.71 },
];
