// ============================================================================
// ResoFlex™ Enterprise OS v4.1 — Domain Registry
// ----------------------------------------------------------------------------
// Declarative map of the 16 business domains: modules, status, permissions,
// and event wiring. Admin navigation and the production checklist read from
// here so the org chart of the platform lives in exactly one place.
// ============================================================================

import type { DomainDescriptor, DomainId, Permission } from "./types";

const rw = (id: DomainId): Permission[] => [`${id}:read`, `${id}:write`, `${id}:admin`];

export const DOMAINS: Record<DomainId, DomainDescriptor> = {
  identity: {
    id: "identity",
    name: "Identity OS",
    summary: "Authentication, organizations, sessions, API keys, feature flags.",
    status: "partial",
    adminRoute: "/admin",
    permissions: rw("identity"),
    publishes: ["user.registered"],
    subscribes: [],
    modules: [
      { key: "auth", label: "Authentication (Google + email)", status: "live", reuses: ["src/hooks/useAuth.ts", "src/routes/auth.tsx"] },
      { key: "profiles", label: "Profiles", status: "live", reuses: ["public.profiles"] },
      { key: "roles", label: "Roles & RBAC", status: "live", reuses: ["public.user_roles", "has_role()"] },
      { key: "organizations", label: "Organizations", status: "planned" },
      { key: "orgMembers", label: "Organization members", status: "planned" },
      { key: "orgSettings", label: "Organization settings", status: "planned" },
      { key: "apiKeys", label: "API keys", status: "planned" },
      { key: "devices", label: "Devices", status: "planned" },
      { key: "sessions", label: "Sessions", status: "planned" },
      { key: "loginHistory", label: "Login history", status: "planned" },
      { key: "mfa", label: "MFA readiness", status: "planned" },
      { key: "oauthProviders", label: "OAuth providers", status: "partial", reuses: ["Lovable OAuth broker", "src/routes/[.]lovable.oauth.consent.tsx"] },
      { key: "featureFlags", label: "Feature flags", status: "planned" },
    ],
  },
  customerIntelligence: {
    id: "customerIntelligence",
    name: "Customer Intelligence OS",
    summary: "One source of truth per customer: health, goals, journey, value.",
    status: "partial",
    permissions: rw("customerIntelligence"),
    publishes: ["lead.created", "membership.upgraded", "referral.activated"],
    subscribes: ["order.created", "payment.verified", "chat.completed"],
    modules: [
      { key: "customerProfile", label: "Customer profile", status: "partial", reuses: ["public.profiles", "src/lib/identity.ts"] },
      { key: "healthProfile", label: "Health profile", status: "planned" },
      { key: "goals", label: "Goals", status: "planned" },
      { key: "preferences", label: "Preferences", status: "planned" },
      { key: "assessment", label: "Assessment", status: "partial", reuses: ["src/routes/personalize.tsx"] },
      { key: "journey", label: "Journey", status: "planned" },
      { key: "membership", label: "Membership", status: "partial", reuses: ["src/platform/membershipRegistry.ts"] },
      { key: "referral", label: "Referral", status: "partial", reuses: ["src/platform/attribution.ts"] },
      { key: "wallet", label: "Wallet", status: "partial", reuses: ["profiles.reso_coins"] },
      { key: "ltv", label: "Lifetime value", status: "planned" },
      { key: "engagementScore", label: "Engagement score", status: "planned" },
      { key: "stage", label: "Customer stage", status: "planned" },
    ],
  },
  commerce: {
    id: "commerce",
    name: "Commerce OS",
    summary: "Catalog, pricing, discounts, inventory and warehouse ledgers.",
    status: "partial",
    permissions: rw("commerce"),
    publishes: ["recommendation.generated"],
    subscribes: ["order.created"],
    modules: [
      { key: "products", label: "Products", status: "live", reuses: ["src/lib/shopify.ts", "src/lib/products.ts"] },
      { key: "variants", label: "Variants", status: "live", reuses: ["Shopify Storefront API"] },
      { key: "collections", label: "Collections", status: "partial", reuses: ["src/routes/shop.tsx"] },
      { key: "categories", label: "Categories", status: "partial" },
      { key: "bundles", label: "Bundles", status: "partial", reuses: ["src/routes/personalize.tsx"] },
      { key: "pricing", label: "Pricing", status: "partial", reuses: ["src/platform/productRegistry.ts"] },
      { key: "discounts", label: "Discounts", status: "planned" },
      { key: "coupons", label: "Coupons", status: "planned" },
      { key: "inventory", label: "Inventory", status: "planned" },
      { key: "warehouses", label: "Warehouses", status: "planned" },
      { key: "inventoryLedger", label: "Inventory ledger", status: "planned" },
      { key: "stockMovements", label: "Stock movements", status: "planned" },
      { key: "suppliers", label: "Supplier metadata", status: "planned" },
      { key: "intelligence", label: "Product performance score", status: "live", reuses: ["src/lib/productIntelligence.ts"] },
    ],
  },
  orders: {
    id: "orders",
    name: "Order Management",
    summary: "Orders, shipments, returns, refunds, timeline and status engine.",
    status: "planned",
    permissions: rw("orders"),
    publishes: ["order.created"],
    subscribes: ["payment.verified"],
    modules: [
      { key: "orders", label: "Orders", status: "partial", reuses: ["Shopify checkout"] },
      { key: "orderItems", label: "Order items", status: "planned" },
      { key: "shipment", label: "Shipment", status: "planned" },
      { key: "shipmentEvents", label: "Shipment events", status: "planned" },
      { key: "returns", label: "Returns", status: "planned" },
      { key: "refunds", label: "Refunds", status: "planned" },
      { key: "exchanges", label: "Exchange requests", status: "planned" },
      { key: "giftCards", label: "Gift cards", status: "planned" },
      { key: "timeline", label: "Order timeline", status: "planned" },
      { key: "statusEngine", label: "Order status engine", status: "planned" },
    ],
  },
  finance: {
    id: "finance",
    name: "Financial Control Plane",
    summary: "Wallets, ledgers, settlements, payouts, reconciliation, exports.",
    status: "planned",
    permissions: rw("finance"),
    publishes: ["payment.verified"],
    subscribes: ["order.created", "subscription.renewed"],
    modules: [
      { key: "wallet", label: "Wallet", status: "planned" },
      { key: "walletTransactions", label: "Wallet transactions", status: "planned" },
      { key: "revenueLedger", label: "Revenue ledger", status: "planned" },
      { key: "settlementLedger", label: "Settlement ledger", status: "planned" },
      { key: "payouts", label: "Payouts", status: "planned" },
      { key: "providerAccounts", label: "Provider accounts", status: "planned" },
      { key: "reports", label: "Financial reports", status: "planned" },
      { key: "bankExport", label: "Bank export", status: "planned" },
      { key: "reconciliation", label: "Automatic reconciliation", status: "planned" },
      { key: "paystack", label: "Paystack", status: "partial", reuses: ["src/platform/services.ts"] },
      { key: "stripe", label: "Stripe (ready)", status: "planned" },
      { key: "flutterwave", label: "Flutterwave (ready)", status: "planned" },
    ],
  },
  subscriptions: {
    id: "subscriptions",
    name: "Subscription Platform",
    summary: "Plans, billing cycles, invoices, renewals, membership unlocks.",
    status: "planned",
    permissions: rw("subscriptions"),
    publishes: ["subscription.renewed", "membership.upgraded", "dashboard.unlocked"],
    subscribes: ["payment.verified"],
    modules: [
      { key: "subscriptions", label: "Subscriptions", status: "planned" },
      { key: "plans", label: "Plans (7/30/60/90 day, VIP, Enterprise)", status: "partial", reuses: ["src/platform/membershipRegistry.ts"] },
      { key: "billingCycles", label: "Billing cycles", status: "planned" },
      { key: "invoices", label: "Invoices", status: "planned" },
      { key: "paymentMethods", label: "Payment methods", status: "planned" },
      { key: "renewals", label: "Renewals", status: "planned" },
      { key: "unlocks", label: "Membership unlocks / premium access", status: "planned" },
    ],
  },
  chatb2k: {
    id: "chatb2k",
    name: "ChatB2K AI OS",
    summary: "Agents, runs, memory, prompts, retrieval, explainable coaching.",
    status: "partial",
    permissions: rw("chatb2k"),
    publishes: ["chat.completed", "recommendation.generated"],
    subscribes: ["lead.created", "order.created"],
    modules: [
      { key: "agentRegistry", label: "Agent registry", status: "partial", reuses: ["src/lib/mcp/index.ts"] },
      { key: "agentRuns", label: "Agent runs", status: "planned" },
      { key: "agentMemory", label: "Agent memory", status: "planned" },
      { key: "promptLibrary", label: "Prompt library", status: "planned" },
      { key: "knowledgeSources", label: "Knowledge sources", status: "partial", reuses: ["src/content/knowledge.ts"] },
      { key: "embeddings", label: "Embeddings", status: "planned" },
      { key: "retrieval", label: "Retrieval", status: "planned" },
      { key: "recommendations", label: "Recommendations", status: "partial", reuses: ["src/components/RecommendedProducts.tsx"] },
      { key: "summary", label: "Conversation summary", status: "planned" },
      { key: "coachActions", label: "Coach actions", status: "planned" },
      { key: "analytics", label: "Conversation analytics", status: "planned" },
    ],
  },
  health: {
    id: "health",
    name: "Health Intelligence",
    summary: "Assessments, metrics, logs, recovery, habits, transformation.",
    status: "planned",
    permissions: rw("health"),
    publishes: ["recommendation.generated"],
    subscribes: ["chat.completed"],
    modules: [
      { key: "assessments", label: "Assessments", status: "partial", reuses: ["src/routes/personalize.tsx"] },
      { key: "bodyMetrics", label: "Body metrics", status: "planned" },
      { key: "nutritionLogs", label: "Nutrition logs", status: "planned" },
      { key: "workoutLogs", label: "Workout logs", status: "planned" },
      { key: "sleep", label: "Sleep", status: "planned" },
      { key: "recovery", label: "Recovery", status: "planned" },
      { key: "habits", label: "Habits", status: "planned" },
      { key: "progressPhotos", label: "Progress photos", status: "planned" },
      { key: "coachRecs", label: "Coach recommendations", status: "planned" },
      { key: "productRecs", label: "Product recommendations", status: "partial" },
      { key: "timeline", label: "Body transformation timeline", status: "planned" },
    ],
  },
  marketing: {
    id: "marketing",
    name: "Marketing OS",
    summary: "Campaigns, segments, templates, automation, lead scoring.",
    status: "partial",
    permissions: rw("marketing"),
    publishes: ["lead.created", "referral.activated"],
    subscribes: ["user.registered", "order.created"],
    modules: [
      { key: "campaigns", label: "Campaigns", status: "planned" },
      { key: "segments", label: "Segments", status: "planned" },
      { key: "emailTemplates", label: "Email templates", status: "planned" },
      { key: "smsTemplates", label: "SMS templates", status: "planned" },
      { key: "whatsappTemplates", label: "WhatsApp templates", status: "partial", reuses: ["src/components/WhatsAppFloat.tsx"] },
      { key: "flows", label: "Automation flows", status: "partial", reuses: ["Make.com pipeline"] },
      { key: "flowRuns", label: "Automation runs", status: "planned" },
      { key: "referralCampaigns", label: "Referral campaigns", status: "planned" },
      { key: "leadSources", label: "Lead sources (RSID/UTM)", status: "live", reuses: ["src/lib/attribution.ts", "src/platform/attribution.ts"] },
      { key: "leadScoring", label: "Lead scoring", status: "planned" },
    ],
  },
  experience: {
    id: "experience",
    name: "Experience OS",
    summary: "Funnels, CTA clicks, scroll depth, A/B tests, conversion events.",
    status: "partial",
    permissions: rw("experience"),
    publishes: [],
    subscribes: [],
    modules: [
      { key: "landingPages", label: "Landing pages", status: "live" },
      { key: "funnels", label: "Funnels", status: "partial" },
      { key: "ctaClicks", label: "CTA clicks", status: "live", reuses: ["src/lib/tracking.ts"] },
      { key: "videoCompletion", label: "Video completion", status: "live", reuses: ["src/components/CinematicWellnessExperience.tsx"] },
      { key: "scrollDepth", label: "Scroll depth", status: "planned" },
      { key: "heatmap", label: "Heatmap events", status: "planned" },
      { key: "abTests", label: "A/B tests", status: "live", reuses: ["src/lib/revenueOS.ts"] },
      { key: "conversionEvents", label: "Conversion events", status: "live", reuses: ["src/lib/pixels.ts"] },
      { key: "dashboardUsage", label: "Dashboard usage", status: "planned" },
      { key: "membershipUsage", label: "Membership usage", status: "planned" },
    ],
  },
  notifications: {
    id: "notifications",
    name: "Notification Center",
    summary: "Queued multi-channel delivery with retry, priority, failover.",
    status: "planned",
    permissions: rw("notifications"),
    publishes: ["notification.sent"],
    subscribes: [
      "user.registered",
      "payment.verified",
      "order.created",
      "subscription.renewed",
      "dashboard.unlocked",
      "referral.activated",
    ],
    modules: [
      { key: "email", label: "Email (Resend)", status: "partial", reuses: ["src/platform/services.ts"] },
      { key: "sms", label: "SMS", status: "planned" },
      { key: "whatsapp", label: "WhatsApp", status: "partial" },
      { key: "push", label: "Push", status: "planned" },
      { key: "telegram", label: "Telegram", status: "planned" },
      { key: "inApp", label: "In-app", status: "planned" },
      { key: "adminAlerts", label: "Admin alerts", status: "planned" },
      { key: "queue", label: "Queue + retry + priority", status: "planned" },
      { key: "delivery", label: "Delivery tracking", status: "planned" },
      { key: "failover", label: "Provider failover", status: "planned" },
    ],
  },
  knowledge: {
    id: "knowledge",
    name: "Knowledge Platform",
    summary: "Articles, protocols, meal and workout libraries, AI retrieval.",
    status: "partial",
    permissions: rw("knowledge"),
    publishes: [],
    subscribes: [],
    modules: [
      { key: "articles", label: "Knowledge articles", status: "live", reuses: ["src/content/knowledge.ts", "src/routes/knowledge.tsx"] },
      { key: "protocols", label: "Protocols", status: "partial", reuses: ["src/content/programs.ts"] },
      { key: "mealLibrary", label: "Meal library", status: "planned" },
      { key: "workoutLibrary", label: "Workout library", status: "planned" },
      { key: "education", label: "Education", status: "partial" },
      { key: "faq", label: "FAQ", status: "planned" },
      { key: "embeddings", label: "Embeddings", status: "planned" },
      { key: "searchIndex", label: "Search index", status: "planned" },
      { key: "retrieval", label: "AI retrieval", status: "planned" },
    ],
  },
  compliance: {
    id: "compliance",
    name: "Compliance OS",
    summary: "Audit logs, security events, consent, policy, risk, evidence.",
    status: "planned",
    permissions: rw("compliance"),
    publishes: [],
    subscribes: ["user.registered", "payment.verified", "order.created"],
    modules: [
      { key: "auditLogs", label: "Audit logs", status: "planned" },
      { key: "financialAudit", label: "Financial audit", status: "planned" },
      { key: "securityEvents", label: "Security events", status: "planned" },
      { key: "accessReviews", label: "Access reviews", status: "planned" },
      { key: "consent", label: "Consent registry", status: "planned" },
      { key: "policyVersions", label: "Policy versions", status: "partial", reuses: ["/privacy", "/terms"] },
      { key: "riskRegister", label: "Risk register", status: "planned" },
      { key: "evidenceVault", label: "Evidence vault", status: "planned" },
      { key: "dataRequests", label: "Data requests", status: "planned" },
      { key: "securityReports", label: "Security reports", status: "planned" },
      { key: "rls", label: "Least-privilege RLS", status: "partial", reuses: ["existing policies + has_role()"] },
    ],
  },
  integrations: {
    id: "integrations",
    name: "Integration Hub",
    summary: "Provider registry, webhook manager, logs, retries, health.",
    status: "partial",
    permissions: rw("integrations"),
    publishes: [],
    subscribes: [],
    modules: [
      { key: "paystack", label: "Paystack", status: "partial" },
      { key: "shopify", label: "Shopify", status: "live", reuses: ["src/lib/shopify.ts"] },
      { key: "make", label: "Make.com", status: "live", reuses: ["src/lib/tracking.ts"] },
      { key: "resend", label: "Resend", status: "partial" },
      { key: "google", label: "Google (auth + GA4)", status: "live" },
      { key: "meta", label: "Meta pixel + CAPI", status: "partial", reuses: ["src/lib/pixels.ts"] },
      { key: "tiktok", label: "TikTok pixel", status: "partial", reuses: ["src/lib/pixels.ts"] },
      { key: "twilio", label: "Twilio", status: "planned" },
      { key: "webhookManager", label: "Webhook manager", status: "planned" },
      { key: "logs", label: "Integration logs", status: "planned" },
      { key: "retryQueue", label: "Retry queue", status: "planned" },
      { key: "health", label: "Health status", status: "partial", reuses: ["src/platform/env.ts"] },
    ],
  },
  operations: {
    id: "operations",
    name: "Operations OS",
    summary: "Jobs, cron history, deployments, health, flags, incidents.",
    status: "planned",
    permissions: rw("operations"),
    publishes: [],
    subscribes: [],
    modules: [
      { key: "jobs", label: "Background jobs", status: "planned" },
      { key: "cronHistory", label: "Cron history", status: "planned" },
      { key: "deployments", label: "Deployment history", status: "planned" },
      { key: "systemHealth", label: "System health", status: "partial", reuses: ["src/platform/ProductionChecklist.ts"] },
      { key: "queueMonitor", label: "Queue monitor", status: "planned" },
      { key: "featureFlags", label: "Feature flags", status: "planned" },
      { key: "featureAssignments", label: "Feature assignments", status: "planned" },
      { key: "incidents", label: "Incident reports", status: "planned" },
      { key: "healthDashboard", label: "Health dashboard", status: "planned" },
    ],
  },
  media: {
    id: "media",
    name: "Media Platform",
    summary: "Assets, variants, optimization, CDN metadata, usage tracking.",
    status: "partial",
    permissions: rw("media"),
    publishes: [],
    subscribes: [],
    modules: [
      { key: "assets", label: "Media assets", status: "partial", reuses: ["src/assets", "Supabase storage"] },
      { key: "library", label: "Media library", status: "planned" },
      { key: "video", label: "Video assets", status: "partial", reuses: ["src/components/CinematicWellnessExperience.tsx"] },
      { key: "imageVariants", label: "Image variants", status: "partial", reuses: ["src/components/ProductImage.tsx"] },
      { key: "optimization", label: "Optimization", status: "live", reuses: ["src/lib/imagePriority.ts"] },
      { key: "lazyLoading", label: "Lazy loading", status: "live" },
      { key: "cdn", label: "CDN metadata", status: "planned" },
      { key: "usage", label: "Usage tracking", status: "partial" },
    ],
  },
};

export const DOMAIN_LIST: DomainDescriptor[] = Object.values(DOMAINS);

export function getDomain(id: DomainId): DomainDescriptor {
  return DOMAINS[id];
}

/** Progress rollup per domain — powers the executive/operations dashboards. */
export function domainProgress(id: DomainId): { live: number; partial: number; planned: number; total: number } {
  const modules = DOMAINS[id].modules;
  return {
    live: modules.filter((m) => m.status === "live").length,
    partial: modules.filter((m) => m.status === "partial").length,
    planned: modules.filter((m) => m.status === "planned").length,
    total: modules.length,
  };
}
