insert into public.resofit_event_contracts (event_name, contract_version, description, required_fields, payload_schema, critical)
values
('wellness.location_detected','1.0','Visitor location resolved for Wellness discovery.',array['latitude','longitude','source'],jsonb_build_object('type','object','properties',jsonb_build_object('latitude',jsonb_build_object('type','number'),'longitude',jsonb_build_object('type','number'),'source',jsonb_build_object('type','string'))),false),
('wellness.state_selected','1.0','Visitor selected a Wellness state.',array['state_slug'],jsonb_build_object('type','object','properties',jsonb_build_object('state_slug',jsonb_build_object('type','string'))),false),
('wellness.city_selected','1.0','Visitor selected a Wellness city.',array['state_slug','city_slug'],jsonb_build_object('type','object','properties',jsonb_build_object('state_slug',jsonb_build_object('type','string'),'city_slug',jsonb_build_object('type','string'))),false),
('wellness.hub_viewed','1.0','Visitor viewed a verified Wellness hub.',array['hub_code'],jsonb_build_object('type','object','properties',jsonb_build_object('hub_code',jsonb_build_object('type','string'))),false),
('wellness.service_viewed','1.0','Visitor viewed a Wellness hub service.',array['hub_code','service_id'],jsonb_build_object('type','object','properties',jsonb_build_object('hub_code',jsonb_build_object('type','string'),'service_id',jsonb_build_object('type','string'))),false),
('wellness.availability_requested','1.0','Visitor requested Wellness service availability.',array['hub_code','service_id'],jsonb_build_object('type','object','properties',jsonb_build_object('hub_code',jsonb_build_object('type','string'),'service_id',jsonb_build_object('type','string'))),false),
('wellness.booking_started','1.0','Visitor started a Wellness booking flow.',array['hub_code','service_id','booking_method'],jsonb_build_object('type','object','properties',jsonb_build_object('hub_code',jsonb_build_object('type','string'),'service_id',jsonb_build_object('type','string'),'booking_method',jsonb_build_object('type','string'))),true),
('wellness.escalation_requested','1.0','Visitor requested human assistance for Wellness.',array['reason'],jsonb_build_object('type','object','properties',jsonb_build_object('reason',jsonb_build_object('type','string'))),false)
on conflict (event_name, contract_version) do update set description=excluded.description,required_fields=excluded.required_fields,payload_schema=excluded.payload_schema,critical=excluded.critical,updated_at=now();
